version: '3.9'

services:
  dev:
    container_name: event_manager_dev
    image: event-manager-api-dev:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 3001:9229
    networks:
      - event-manager-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - event-manager-network
    restart: always

  prod:
    container_name: event_manager_prod
    image: event-manager-api-prod:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - event-manager-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    
networks:
  event-manager-network:
    driver: bridge

volumes:
  db: